apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: api-gateway

commonLabels:
  env: dev
  app: kong

secretGenerator:
- name: kong-db-secrets
  namespace: api-gateway
  literals:
  - POSTGRES_DB=kong
  - POSTGRES_USER=kong
  - POSTGRES_PASSWORD=password
- name: kong-secret
  namespace: api-gateway
  literals:
  - KONG_DATABASE=postgres
  - KONG_PG_HOST=kong-db
  - KONG_PG_USER=kong
  - KONG_PG_PASSWORD=password

configMapGenerator:
- name: kong-config
  namespace: api-gateway
  literals:
  - KONG_PROXY_ACCESS_LOG=/dev/stdout
  - KONG_ADMIN_ACCESS_LOG=/dev/stdout
  - KONG_PROXY_ERROR_LOG=/dev/stderr
  - KONG_ADMIN_ERROR_LOG=/dev/stderr
  - KONG_ADMIN_LISTEN=0.0.0.0:8001
  - KONG_ADMIN_GUI_URL=http://localhost:8002

