version: '3'

volumes:
    kong-db:

services:
    kong-db:
        image: postgres:13
        container_name: kong-db
        volumes:
            - kong-db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: kong
            POSTGRES_USER: kong
            POSTGRES_PASSWORD: password

    db-prep:
        image: kong/kong-gateway:3.5.0.0
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-db
            KONG_PG_PASSWORD: password
            KONG_PASSWORD: password
        command: kong migrations bootstrap

    kong:
        image: kong/kong-gateway:3.5.0.0
        depends_on: [db-prep]
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
            - 8002:8002
            - 8445:8445
            # - 8003:8003
            # - 8004:8004
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-db
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: password
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001
            KONG_ADMIN_GUI_URL: http://localhost:8002
